apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ulyq4g5kp-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c024a4276c.iw9z.p3.openshiftapps.com/rhtap/rhtap-qe-python:394796389add6f03561ec098cf36fb42cdcb48e6@sha256:4162803a15720e08d6920789906879244c02cee3ce1bade14fb41b25278cb07d
          name: container-image
