apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ulyq4g5kp-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ulyq4g5kp-python 
  name: ulyq4g5kp-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ulyq4g5kp-python 
